### ISSUE TITLE
Regarding 'dataset.py'

### ISSUE THREAD

**Issue by RACHLEB** [wjtan99/BERT_Anomaly_Video_Classification#2]
When referring to the UCF-crime dataset within 'dataset.py', two txt files are called:

` train_file = 'train_normal.txt'
  test_file = 'test_normalv3.txt'`

I cannot find these txt files in any of the UCF-dataset versions or txt file splits. 

Where can I find these files?

Thanks!

**Comment by wjtan99** [comment]
Please refer to MIL-BERT/fix_ucf_crime_test_list.ipynb how the test files are generated. The train_normal.txt is generated similarly. We generate these files so to make our coding easier.

**Comment by wjtan99** [comment]
The training file is similar to https://github.com/tianyu0207/RTFM/blob/main/list/ucf-i3d.list.
